/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.ArrayList;
import java.util.List;
import static proyecto.RegistarProducto.visualizar_productos_en_la_lista;

/**
 *
 * @author DAVID
 */
public class RegistrarMenu extends javax.swing.JFrame {
    
    protected static String tipo;
    

    /**
     * Creates new form RegistrarProductos
     */
    public RegistrarMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Menu Registrar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comestibles = new javax.swing.JButton();
        utensilios = new javax.swing.JButton();
        oficina = new javax.swing.JButton();
        industriales = new javax.swing.JButton();
        atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Tipos de Productos");

        comestibles.setBackground(new java.awt.Color(153, 153, 153));
        comestibles.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        comestibles.setText("Comestibles");
        comestibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comestiblesActionPerformed(evt);
            }
        });

        utensilios.setBackground(new java.awt.Color(153, 153, 153));
        utensilios.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        utensilios.setText("Utensilios");
        utensilios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utensiliosActionPerformed(evt);
            }
        });

        oficina.setBackground(new java.awt.Color(153, 153, 153));
        oficina.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        oficina.setText("Oficina");
        oficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oficinaActionPerformed(evt);
            }
        });

        industriales.setBackground(new java.awt.Color(153, 153, 153));
        industriales.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        industriales.setText("Industriales");
        industriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrialesActionPerformed(evt);
            }
        });

        atras.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(atras)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(utensilios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(industriales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oficina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comestibles))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(comestibles, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(utensilios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oficina, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(industriales, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(atras)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comestiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comestiblesActionPerformed
        RegistarProducto registarProducto = new RegistarProducto();
        registarProducto.show();
        
        tipo = "Comestibles"; // tipo de producto a registrar
        RegistarProducto.tipoPr.setText(tipo); // muestro el tipo de producto en la interfaz de registrar
        
        this.setVisible(false); // oculto esta ventana
        RegistarProducto.visualizar_productos_en_la_lista(); // muestro los datos de productos registrados
    }//GEN-LAST:event_comestiblesActionPerformed

    private void utensiliosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utensiliosActionPerformed
        // TODO add your handling code here:
        RegistarProducto registarProducto = new RegistarProducto();
        registarProducto.show();
        
        tipo = "Utensillos"; // tipo de producto a registrar
        RegistarProducto.tipoPr.setText(tipo); // muestro el tipo de producto en la interfaz de registrar
        
        this.setVisible(false); // oculto esta ventana
        RegistarProducto.visualizar_productos_en_la_lista(); // muestro los datos de productos registrados
    }//GEN-LAST:event_utensiliosActionPerformed

    private void industrialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrialesActionPerformed
        // TODO add your handling code here:
        RegistarProducto registarProducto = new RegistarProducto();
        registarProducto.show();
        
        tipo = "Industriales"; // tipo de producto a registrar
        RegistarProducto.tipoPr.setText(tipo); // muestro el tipo de producto en la interfaz de registrar
        
        this.setVisible(false); // oculto esta ventana
        RegistarProducto.visualizar_productos_en_la_lista(); // muestro los datos de productos registrados
    }//GEN-LAST:event_industrialesActionPerformed

    private void oficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oficinaActionPerformed
        // TODO add your handling code here:
        RegistarProducto registarProducto = new RegistarProducto();
        registarProducto.show();
        
        tipo = "Oficina"; // tipo de producto a registrar
        RegistarProducto.tipoPr.setText(tipo); // muestro el tipo de producto en la interfaz de registrar
        
        this.setVisible(false); // oculto esta ventana
        RegistarProducto.visualizar_productos_en_la_lista(); // muestro los datos de productos registrados
    }//GEN-LAST:event_oficinaActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton comestibles;
    private javax.swing.JButton industriales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton oficina;
    private javax.swing.JButton utensilios;
    // End of variables declaration//GEN-END:variables
}
